services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: employee_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://admin:password@database:5432/employee_management
      - JWT_SECRET=dev-secret-key
    ports:
      - "3001:3001"
    depends_on:
      - database
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "sleep 5 && npx prisma generate && npx prisma migrate deploy && npx prisma db seed && npm run dev"

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: