-- AlterTable
ALTER TABLE "requests" ADD COLUMN     "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "description" SET DATA TYPE VARCHAR(1000),
ALTER COLUMN "summary" SET DATA TYPE VARCHAR(200);
